org: zhaoelton
app: serverless_python_template
service: serverless_python_template

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - venv/**

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  environment:
    DEFAULT_PROJECT: ${param:DEFAULT_PROJECT}
    API_TOKEN : ${param:API_TOKEN}
    USER_NAME : ${param:USER_NAME}
    SERVER : ${param:SERVER}

functions:

  echo:
    handler: handler.echo
    events:
      - http:
          path: /echo
          method: post



